import 'dart:io';

import 'package:basic_utils/basic_utils.dart';

import 'extensions.dart';
import 'mobinsaHttpServer.dart';



String certPath = !DEBUG ? "${getExecutableAbsolutePath()}${slash}..${slash}files${slash}cert.pem": "cert.pem";
String keyPath = !DEBUG ? "${getExecutableAbsolutePath()}${slash}..${slash}files${slash}key.pem": "key.pem";


/// Verifies if a certifcate was generated by the software
///
/// Return false if no certificate was found, true otherwise
Future<bool> checkForCertificate() async{
  if (!File(certPath).existsSync() || !File(keyPath).existsSync()){
    return false;
  }
  try{
    SecurityContext? context = SecurityContext()
      ..useCertificateChain(keyPath) // certificat (ou chaîne complète)
      ..usePrivateKey(certPath);
    context = null;
    return true;
  }
  catch (e,s){
    return false;
  }
  return true;

}
/// Function which generates a self-signed X509 certificate to serve the HTTPS webapp
Future<void> generateCertificateWithBasicUtils() async {
  if (await checkForCertificate()){
    print("Certificate already exists");
    return;
  }
  // Générer une paire de clés RSA
  final keyPair = CryptoUtils.generateRSAKeyPair(keySize: 2048);
  final secondKeyPair = CryptoUtils.generateEcKeyPair();
  // Créer les informations du certificat
  final dn = {
    'CN': 'localhost',
    'O': "Mob'INSA Software",
    'C': 'FR',
  };
  var privKey = secondKeyPair.privateKey as ECPrivateKey;
  var pubKey = secondKeyPair.publicKey as ECPublicKey;
  // Créer le certificat auto-signé

  final csr = X509Utils.generateEccCsrPem(dn, privKey, pubKey);
  // Convertir en format PEM
  var x509PEM = X509Utils.generateSelfSignedCertificate(secondKeyPair.privateKey, csr, 365);
  final keyPem = CryptoUtils.encodeEcPrivateKeyToPem(secondKeyPair.privateKey as ECPrivateKey);
  // Sauvegarder les fichiers
  File certFile = File(certPath);
  File keyFile = File(keyPath);
  if (!certFile.existsSync()){
    certFile.createSync(recursive: true);
  }
  if (!keyFile.existsSync()){
    certFile.createSync(recursive: true);
  }
  // Saving the cert.pem file
  certFile.writeAsStringSync(x509PEM);
  // Saving the key.pem file
  keyFile.writeAsStringSync(keyPem);

  print('Certificat généré avec basic_utils :');
  print('- cert.pem');
  print('- key.pem');
}