name: mobinsaHttpServer
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  basic_utils: ^5.8.2
  dart_jsonwebtoken: ^3.2.0
  pointycastle: ^4.0.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3
  shelf_web_socket: ^3.0.0
  uuid: ^4.5.1



